### PR TITLE
Bring fork up-to-date and fix method-override issue

### LINKED ISSUE #924: Elasticsearch::Model overrides class .search method
Hello. I've updated from `elasticsearch-model` 6.1.0 version to the latest 7.0.0 and got a silly bug. I have the following structure:

```ruby
class Article
  include Searchable
end
```

and 

```ruby
class Searchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
  end

  class_methods do
    def search(term)
      # my logic here
    end
  end
end
```

When I call `Article.search` I expect my method to be called, and it worked such before. With the `elasticsearch-model` 7.0.0 the delegated `Article.__elasticsearch__.search` is called directly. 

I found the reason in the code: https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model.rb#L115

```ruby
    def self.included(base)
      base.class_eval do
        include Elasticsearch::Model::Proxy

        # Delegate common methods to the `__elasticsearch__` ClassMethodsProxy, unless they are defined already
        class << self
          METHODS.each do |method|
            delegate method, to: :__elasticsearch__ unless self.respond_to?(method)
          end
        end
      end

      # Add to the model to the registry if it's a class (and not in intermediate module)
      Registry.add(base) if base.is_a?(Class)
    end
```

The problem is that `self` from `self.respond_to?` is a singleton class of `Article` class and of course it doesn't respond to search. It's in its public instance methods. 

It was changed 8 months ago here https://github.com/elastic/elasticsearch-rails/commit/f9a87ff3d07a6a95c771ed34f348f71e0f856221#diff-bada22348f9db4f589962054cc9adcb7R115, and I wonder how this was unnoticeable for such a long period. Am I missing something?

The previous implementation was right: `delegate method, to: :__elasticsearch__ unless self.public_instance_methods.include?(method)`

### PR DESCRIPTION
**Pull request by papanikge**
This PR is a "hard reset" on the tag `v7.1.0` which is our current bundled version
plus
two more commits that fix https://github.com/elastic/elasticsearch-rails/issues/924

### CODE REVIEW

**Comment by papanikge** [comment]
@greenonion only review the last two commits

File: elasticsearch-model/spec/elasticsearch/model/module_spec.rb [hunk 1]
```diff
@@ -47,7 +47,7 @@ def self.search(query, options={})
         end
       end
 
-      DummyIncludingModel.__send__ :include, Elasticsearch::Model
+      DummyIncludingModelWithSearchMethodDefined.__send__ :include, Elasticsearch::Model
```
Comment (greenonion) [inline elasticsearch-model/spec/elasticsearch/model/module_spec.rb:51]: I think you need both lines, no?

Comment (papanikge) [reply elasticsearch-model/spec/elasticsearch/model/module_spec.rb:51]: do I? wow good catch

Comment (greenonion) [reply elasticsearch-model/spec/elasticsearch/model/module_spec.rb:51]: haha yeah I think you do, so you can test both scenarios. I was reading the code yesterday :)

Comment (papanikge) [reply elasticsearch-model/spec/elasticsearch/model/module_spec.rb:51]: changed

**Review by greenonion — APPROVED** [review]
LGTM!

**Comment by papanikge** [comment]
`skroutz` main branch rebased. moving w/ the merge.
